export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'
export const AUTH_ERROR = 'AUTH_ERROR'

export const DID_GET_ISSUES = 'DID_GET_ISSUES'
export const REMOVE_ISSUES = 'REMOVE_ISSUES'
export const MODIFY_ISSUES = 'MODIFY_ISSUES'

export const DISPLAY_ISSUE = 'DISPLAY_ISSUE'
export const UPDATE_DISPLAY_ISSUE = 'UPDATE_DISPLAY_ISSUE'
export const REMOVE_DISPLAY_ISSUE = 'REMOVE_DISPLAY_ISSUE'

export const DELETE_ISSUE = 'DELETE_ISSUE'
